#!/bin/bash
. "$(dirname -- "$0")/_/husky.sh"

BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
MAIN_PATTERN_NAME="^(development|production|staging)$"
FEATURE_PATTERN_NAME="^(feat|refactor|fix)/TIC-[0-9]{1,4}$"
ERROR_MESSAGE="ERROR: The branch name does not follow the required pattern ([feat | refactor | fix]/TIC-NUMBER)."

if [[ ! "$BRANCH_NAME" =~ $MAIN_PATTERN_NAME ]] || [[ ! "$BRANCH_NAME" =~ $FEATURE_PATTERN_NAME ]]; then
  exit 0
fi

echo "${ERROR_MESSAGE}"
exit 1
