#!/bin/bash
. "$(dirname -- "$0")/_/husky.sh"

BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
MAIN_PATTERN_NAME="^(development|production|staging)$"
FEATURE_PATTERN_NAME="^(feat|refactor|fix)/TIC-[0-9]{1,4}$"

if [[ "$BRANCH_NAME" =~ $MAIN_PATTERN_NAME ]] || [[ "$BRANCH_NAME" =~ $FEATURE_PATTERN_NAME ]]; then
  exit 0
fi

if [[ ! "$BRANCH_NAME" =~ MAIN_PATTERN_NAME ]] || [[ ! "$BRANCH_NAME" =~ $FEATURE_PATTERN_NAME ]]; then
  echo "⧗   input:  $BRANCH_NAME"
  echo "✖   branch name must be one of:"
  echo "        - [feat, refactor, fix]/TIC-NUMBER"
  echo "        - [development, staging, production]"
  exit 1
fi

exit 1
