#!/bin/bash
. "$(dirname -- "$0")/_/husky.sh"

BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
MAIN_PATTERN_NAME="^(development|production|staging)$"
ERROR_MESSAGE="ERROR: The branch name does not follow the required pattern ([feat | refactor | fix]/TIC-NUMBER)."

if [[ ! "$BRANCH_NAME" =~ $MAIN_PATTERN_NAME ]]; then
  echo "${ERROR_MESSAGE}"
  exit 1
fi

exit 0
